### ISSUE TITLE
Standardize shell usage in README and document differences

### ISSUE THREAD

**Issue by joostslijkoort** [ClinicalGraphics/keycmd#27]
According to the README, commands shall be called using `keycmd command`, while on MacOS commands need to be called like `keycmd "command"`.

Is this expected behaviour, or a misconfiguration on my machine?

**Comment by Korijn** [comment]
That's expected behavior. It's actually not determined by the OS, but by the shell you are using. It is called out in the readme but not in every place. It gets very verbose quickly. If you think you can improve the readme, please feel free to open a pull request.

Example from the README:
https://github.com/ClinicalGraphics/keycmd/blob/255ecdd683e0844811415798c308cd65ba29e919/README.md?plain=1#L119-L121

**Comment by joostslijkoort** [comment]
Very clear! I did not see that part in the readme, but i agree the readme would be filled with clutter if the different types of shells would need to be addressed. Will close this issue.

**Comment by Korijn** [comment]
We can consider adding a separate section to the readme that addresses this, and we can "standardize" the readme to use one specific shell (let's say bash) in its examples throughout.
